services:
  app:
    build: .
    command:
      - scripts/start_app.sh
    ports:
      - "8000:8000"
    env_file:
      - app.env # configure django to connect to database
      - database.env # configure django to authenticate to database
    volumes:
      - .:/usr/src/app/

  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data: # named volumes can be managed easier using docker-compose